name: testflutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.5.2
  just_audio: ^0.9.36
  http: ^1.1.0
  shared_preferences: ^2.2.2
  audio_service: ^0.18.18
  audio_session: ^0.1.19
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
