name: vibra
description: "Vibra Music App - Stream and discover your favorite music."
publish_to: 'none'
version: 0.0.3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.5.2
  http: ^1.1.0
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.0
  smtc_windows: ^0.1.3
  shared_preferences: ^2.2.2
  audio_service: ^0.18.18
  audio_session: ^0.1.19
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.1.4
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  get_it: ^8.2.0
  onesignal_flutter: ^5.2.5
  flutter_dotenv: ^5.1.0
  # Network ecosystem packages
  socket_io_client: ^2.0.3+1
  network_info_plus: ^5.0.3
  multicast_dns: ^0.3.2+6
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true
  assets:
    - .env
  fonts:
    - family: CascadiaCode
      fonts:
        - asset: assets/fonts/CascadiaCode.ttf